version: '3'

services:
  db:
    image: 'postgres:9.6.5'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    env_file:
      - env_file
    networks:
      - db_nw

  reactapp:
    image: node:slim
    volumes:
      - ./frontend:/frontend
      - ./public/:/frontend/build
    command: bash -c "
      cd frontend;
      yarn install;
      yarn build;"

  flaskapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./fixtures:/fixtures
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: 'nginx:1.13.5'
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./public:/public
    networks:
      - web_nw
    depends_on:
      - flaskapp

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata:
